[package]
name = "gitprompt"
version = "0.1.0"
authors = ["Ryan Boehning <1250684+ryboe@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
description = "Generate a zsh prompt that prints the current branch name with colors."

[profile.release]
codegen-units = 1
lto = true
strip = true
